- src/pages/Signup/SignUpContent.js
- src/pages/Signup/SignUpContent.scss
- src/pages/Signup/SignUpForm.js
- src/pages/Signup/SignUpForm.scss
- src/pages/Signup/Signup.js
- src/pages/Signup/Signup.scss
<br />
- 회원가입페이지를 만들고 api주소를 받아 서버에 회원의 정보를 넘기는 것 까지 구현.
<br />
1. 유저의 정보를 받아 객체로 저장
2. 저장한 것을 백엔드에게 전송(전송성공)
<br />
- 객체 스프레드 문법과 구조분해할당을 통해 state하나로 회원의 여러 정보들을 한 번에 관리하는 코드를 작성해봄
<br />
> [38기 박성수] 회원가입 페이지 UI 및 기능

- src/components/Footer/Footer.js
- src/components/Footer/Footer.scss
- src/components/Footer/data.js
<br />
- footer UI구현
<br />
1. footer에는 상수데이터를 별도의 파일로 분리하여 footermenu를 작성하였다
<br />
- 
<br />
-
> [38기 김온누리]Add: footerUI 구현

- src/components/Footer/Footer.js
- src/pages/Cart/Cart.js
- src/pages/Cart/Cart.scss
- src/pages/Cart/CartAside.js
- src/pages/Cart/CartAside.scss
- src/pages/Cart/CartHeader.js
- src/pages/Cart/CartHeader.scss
- src/pages/Cart/CartItem.js
- src/pages/Cart/CartItem.scss
<br />
- 장바구니 페이지 UI구성
<br />
1.  단순 상수데이터 활용 UI구성
2. 추후) 실제 유저가 담은 상품을 받아와 장바구니 페이지 구성 및 데이터 정보를 UI에 나오게
<br />
> [38기 박성수] 장바구니 컴포넌트

- src/components/Nav/Nav.js
<br />
- 아이콘 클릭시 회원가입 => 로그인으로 링크 변경
<br />
1. 링크 변경 완료
<br />
<br />
> [38기 김우진]FIX : Icon Link 수정

- src/components/ItemProduct/ItemProduct.js
<br />
- 아이템의 가격에 ,를 찍어주는 로직 추가
<br />
1. 아이템의 가격에 ,를 찍어주는 로직 추가
<br />
> [38기 박성수] 상품단위 컴포넌트 가격에 ,를 찍어주는 함수 추가

- src/pages/Signup/SignUpForm.js
- src/pages/Signup/Signup.scss
<br />
회원가입에 정규식 포함(이메일, 패스워드)
회원가입 UI구성
<br />
1. 회원가입 : 이전에는 input창만 만들어놓은 상태에서 통신에 성공하였고, 
팀원들의 머지로 변경된사항을 적용하여 추가 css를 적용하였고, 회원가입에 정규식을 포함하였습니다.
<br />
정규식변수를 선언하고 test메서드를 통해 정규식의 조건을 만족하면 true 그렇지 못하다면 false를 반환한다는 것을 알게되었고 적용해보았음.
<br />
#:: 이후 추가할 사항 
현재 css에 input창에 빨갛게 되어있는데 조건에 만족한다면 초록색으로 바뀌게 구현.
> [38기 박성수] 회원가입 UI 및 form 제출조건 추가

- public/data/Navmockdata/navmockdata.json
- src/components/Nav/Nav.js
> [38기 박성수 ]Modify : 네브바 link to경로 수정

- src/Router.js
- src/pages/Delivery/Delivery.js
<br />
path파라미터 고려하여 detail페이지 list페이지  라우트 경로 수정
+ 구매페이지 생성 및 라우터 js에서 구매페이지 연동
> [38기 박성수] HOTFIX : 라우터 경로 path파라미터 고려 재설정

- src/pages/Login/Login.js
- src/pages/Login/Login.scss
<br />
- 아이디, 비밀번호 정규식 조건 추가
<br />
1. 로그인 입력 데이터 유효성 검사 
2. 로그인 데이터 처리 
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
<br />
<br />
> [38기 김온누리]Add: 로그인페이지 이메일 비밀번호 유효성검사기능과  스타일 추가

- src/config.js
<br />
자주 쓰는 api주소와 엔드포인트를 변수화하여 지정하였음
이후에 백엔드에서 api주소가 하나로 합쳐지면 변수도 하나로 재설정할 예정.
> [38기 박성수] Add : api주소를 변수화하는  js파일 생성

- public/data/Navmockdata/navmockdata.json
<br />
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)
<br />
nav바에 있던 링크 경로에 오타가 있어 searchParams제대로 동작하지 않는 현상,,,
오타수정
> [38기 박성수]HOTFIX : 네브바 경로 재설정

- src/components/Footer/Footer.js
<br />
<br />
footer 상수데이터 map 활용시 key 값 누락 수정
<br />
<br />
> [38기 김온누리]HOTFIX:  footer map key값 생성

- public/data/MainSlide.json
- src/pages/Main/Main.scss
- src/pages/Main/components/MainBanner.js
- src/pages/Main/components/MainBanner.scss
- src/pages/Main/components/MainSlide.js
- src/pages/Main/components/MainSlide.scss
<br />
- 캐러셀 아이템 추가될때도 페이지가 자동으로 늘어나고 마지막페이지에서는 항상 마지막 아이템이 꽉차도록 이동한다
<br />
<br />
<br />
계산적인 방법으로 구현했는데 다른 간편한 방법이 있는지 궁금합니다
> [38기 김온누리 ]Main페이지 캐러셀 확장성 고려한 개선사항

- src/pages/Login/Login.js
- src/pages/Login/Login.scss
<br />
- css 최적화
<br />
<br />
<br />
> [38기 김온누리]FIX: 로그인페이지css 중복제거

- src/pages/Signup/SignUpForm.js
- src/pages/Signup/SignUpForm.scss
<br />
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)
<br />
이메일 패스워드 정규식 통과시 색이 초록색으로 변경
나머지 input창은 값이 입력되면 색이 초록색으로 변경되게 함.
> [38기 박성수] SignUp 인풋창 특정 조건 만족시 색이 바뀌는 css적용

- src/Router.js
<br />
itemlist/:gender/:category
>> 성별에 따른 카테고리에 해당하는 아이템만 불러올 수 있도록 경로 재 설정
> [38기 박성수 ]Fix : Router경로재설정 (카테고리별 경로 고려)

- src/config.js
> [38기 박성수]추가 : api carts 주소추가

- public/data/Navmockdata/navmockdata.json
<br />
path parameter고려하여 url 재설정
<br />
Router.js에 경로를 itemlist/:gender/:category로 설정하며
url이 itemlist/men?offset=&limit=8 로 설정되어있어 category에 해당하는 값들을 읽어오지 못해 오류가 발생하였고, 이에 따른 값을 url에 설정해줌
> [38기 박성수] 재수정 : path parameter고려 category설정과정에서 오류발생하여 수정

- public/data/MainSlide.json
- src/pages/Main/components/MainBanner.js
- src/pages/Main/components/MainSlide.js
<br />
- useEffect 내 setInterval 기능 구현
<br />
1. 버튼 클릭 불리언 값으로 슬라이드 재생 및 일시정지 기능구현
<br />
- 원래 커스텀 훅을 이용해 사용하였으나
- useEffect 내 setInterval 실행되는 조건을 추가해 커스텀 훅 없이 기능이 구현되도록 하였다
- 추후 2차 프로젝트에서 재사용성을 고려해 커스텀 훅을 이용해 보면 좋을것같다
<br />
> [38기 김온누리]Modify: 메인아이템 목데이터 키값 변경 및useInterval 커스텀 훅 대체코드 생성

- src/pages/Login/Login.js
- src/pages/Signup/SignUpForm.js
<br />
회원가입 완료시 로그인화면으로 가게하는 로직, 통신 후 에러메세지가 출력되면 경고메세지를 띄우는 로직추가
> [38기 박성수]  Modify : Signup페이지 로직추가

- src/pages/Login/Login.js
<br />
- 로그인 실패시 알림창 생성
<br />
로그인시 비밀번호 유효성 검사는 삭제한 후 이메일 혹은 비밀번호가 틀릴 경우
api 서버에 보내고 에러 메세지로 핸들링 한다
<br />
- 사용자 입장에서 많이 생각 해 볼 수 있었다
<br />
> [38기 김온누리] 로그인페이지 : 에러메세지 핸들링 및 비밀번호 유효검사 삭제

- src/components/Nav/Nav.js
- src/components/Nav/Nav.scss
- src/components/Nav/NavSD.js
<br />
- 장바구니 및 위시리스트 정보 받아와서 숫자 띄워주는 기능 구현
-  코드 더 짧게 만들기 위한 리팩토링 진행
<br />
1. 아이콘 옆에 숫자 띄워주기
- fetch로 장바구니 혹은 위시리스트 총 갯수를 불러온다.
- fetch된 내용이 있다면 아이콘옆에 숫자를 띄워주고 없으면 null로 해당 사항이 보이지 않게 구현.
2. 코드 리팩토링 진행
- 반복되는 링크의 경우 상수데이터를 만들어 map을 통해 기입
<br />
- 백엔드에서 어떤 데이터를 처리해주는지에 대한 생각을 더 많이 해볼수 있게 됨.
- 이중 삼항연산자를 써보려다가 Nulllish coalescing operator 라는 것을 알게됨.
<br />
> [38기 김우진] ADD: Nav바 추가 구현사항 진행

- src/pages/Signup/Signup.scss
<br />
login페이지와 통일성을 고려하여 UI수정
> [38기 박성수]css수정 : width에서 max-width로 수정

- src/components/ItemProduct/ItemProduct.js
- src/pages/Wishlist/Wishlist.js
- src/pages/Wishlist/components/WishProduct.js
<br />
- 데이터 받아올때 소수점 자리까지 받아오는 데이터 소수자리 제거
<br />
2. 로그인 데이터 처리 (예시 - 백엔드)
<br />
<br />
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)
> [38기 김온누리]Hotfix: 위시리스트 페이지 가격 숫자 소수점 제거

- public/data/Navmockdata/navmockdata.json
- src/Router.js
- src/config.js
- src/pages/Itemlist/Itemlist.js
<br />
nav바 경로 재설정
Router경로 /:gender/:category >> /:gender로 수정 (이후 쿼리파라미터)
itemlist의 페이지에 query파라미터로 category추가
> [38기 박성수] path파라미터 > query파라미터 변경으로 인한 Router, Nav 목데이터 , itemlist 경로 및 쿼리 변경

- src/pages/Itemlist/Itemlist.js
<br />
페이지네이션 버튼 3개에서 2개로 변경 (상품수 고려)
> [38기 박성수]상품수 고려 페이지 버튼 수 3개에서 2개로 변경
